# Generated by Django 3.1.6 on 2021-02-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('base', models.CharField(max_length=255)),
                ('encoding', models.CharField(max_length=255)),
            ],
        ),
    ]
